###########################
# Docker compose SCRAMBLE #
###########################
version: '3.9'

services:

    stark-module-structuralvariation-submodule-scramble-service-setup:
        image: stark/stark-module-structuralvariation-submodule-scramble-service-common:3.1
        build:
            context: ./
            dockerfile: scramble_dockerfile
        entrypoint: ["snakemake"]
        command: ["-s", "/app/bin/scramble_setup.smk", "-c1"]
        container_name: stark-module-structuralvariation-submodule-scramble-service-setup
        restart: "no"
        volumes:
            - /home1/data/STARK/services/structuralvariation/scramble:/services/structuralvariation/scramble:rw
            - /home1/data/STARK/config/structuralvariation/scramble:/config/structuralvariation/scramble:rw
            - /home1/data/STARK/databases:/databases:rw
        working_dir: /
        networks:
            - stark_stark

    stark-module-structuralvariation-submodule-scramble-service-cli:
        image: stark/stark-module-structuralvariation-submodule-scramble-service-common:3.1
        build:
            context: ./
            dockerfile: scramble_dockerfile
        container_name: stark-module-structuralvariation-submodule-scramble-service-cli
        restart: "no"
        entrypoint: ["/bin/bash", "-c"]
        command: ["tail -f /dev/null"]  
        tty: true
        stdin_open: true
        volumes:
            - /home1/data/STARK/output/repository:/output/repository:rw
            - /home1/data/STARK/output/depository:/output/depository:rw
            - /home1/data/STARK/services/structuralvariation/scramble/cli:/services/structuralvariation/scramble/cli:rw
            - /home1/data/STARK/config/structuralvariation/scramble/cli:/config/structuralvariation/scramble/cli:ro
            - /home1/data/STARK/databases:/databases:ro
        networks:
            - stark_stark
        healthcheck:
            test:
                [
                    "CMD",
                    "test",
                    "-f",
                    "/services/structuralvariation/scramble/cli/SETUPComplete.txt"
                ]
            timeout: 10s
            interval: 30s
            retries: 480

    stark-module-structuralvariation-submodule-scramble-service-listener:
        image: stark/stark-module-common-submodule-listener-service-listener:2.0
        container_name: stark-module-structuralvariation-submodule-scramble-service-listener
        entrypoint: "python3"
        command: "/app/bin/listener.py --input=/output/repository --json=/config/structuralvariation/scramble/listener/scramble.json --config=/config/structuralvariation/scramble/listener/scramble.conf --servicename=SCRAMBLE --containersfile=/services/structuralvariation/scramble/listener --nbDaysBack=30 --minDelay=1"
        restart: always
        environment:
            - DOCKER_STARK_MODULE_SUBMODULE_INNER_FOLDER_CONFIG=/config/structuralvariation/scramble
        volumes:
            - /home1/data/STARK/output/repository:/output/repository:ro
            - /home1/data/STARK/output/depository:/output/depository:ro
            - /home1/data/STARK/services/structuralvariation/scramble:/services/structuralvariation/scramble:rw
            - /home1/data/STARK/config/structuralvariation/scramble:/config/structuralvariation/scramble:ro
            - /home1/data/STARK/config/structuralvariation/scramble/listener/launcher.py:/app/bin/config/launcher.py:ro
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - stark_stark
        depends_on:
            stark-module-structuralvariation-submodule-scramble-service-cli:
                condition: service_healthy

networks:
    stark_stark:
        external: true
