#########################
# Docker compose fusions #
#########################
version: '3.9'

services:

    stark-module-rnaseq-submodule-fusions-service-setup:
        image: stark/stark-module-rnaseq-submodule-fusions-service-common:1.0
        build:
            context: ./
            dockerfile: fusions_dockerfile
        entrypoint: "snakemake"
        command: "-p -s /app/bin/fusions_setup.smk"
        container_name: stark-module-rnaseq-submodule-fusions-service-setup
        restart: "no"
        volumes:
            - /home1/data/STARK/services/rnaseq/fusions:/services/rnaseq/fusions:rw
            - /home1/data/STARK/config/rnaseq/fusions:/config/rnaseq/fusions:rw
            - /home1/data/STARK/databases:/databases:rw
        working_dir: /
        networks:
            - stark_stark

    stark-module-rnaseq-submodule-fusions-service-cli:
        image: stark/stark-module-rnaseq-submodule-fusions-service-common:1.0
        build:
            context: ./
            dockerfile: fusions_dockerfile
        container_name: stark-module-rnaseq-submodule-fusions-service-cli
        restart: "no"
        entrypoint: ["/bin/bash", "-c"]
        command: ["tail -f /dev/null"]  
        tty: true
        stdin_open: true
        volumes:
            - /home1/data/STARK/output/repository:/output/repository:rw
            - /home1/data/STARK/output/depository:/output/depository:rw
            - /home1/data/STARK/services/rnaseq/fusions/cli:/services/rnaseq/fusions/cli:rw
            - /home1/data/STARK/config/rnaseq/fusions/cli:/config/rnaseq/fusions/cli:ro
            - /home1/data/STARK/databases:/databases:ro
        networks:
            - stark_stark
        healthcheck:
            test:
                [
                    "CMD",
                    "test",
                    "-f",
                    "/services/rnaseq/fusions/cli/SETUPComplete.txt"
                ]
            timeout: 10s
            interval: 60s
            retries: 3600
 
 
    stark-module-rnaseq-submodule-fusions-service-listener:
        image: stark/stark-module-common-submodule-listener-service-listener:2.0
        container_name: stark-module-rnaseq-submodule-fusions-service-listener
        entrypoint: "python3"
        command: "/app/bin/listener.py --input=/output/repository --json=/config/rnaseq/fusions/listener/fusions.json --config=/config/rnaseq/fusions/listener/fusions.conf --servicename=FUSIONS --containersfile=/services/rnaseq/fusions/listener --nbDaysBack=30 --minDelay=1"
        restart: always
        environment:
            - DOCKER_STARK_MODULE_SUBMODULE_INNER_FOLDER_CONFIG=/config/rnaseq/fusions
        volumes:
            - /home1/data/STARK/output/repository:/output/repository:ro
            - /home1/data/STARK/output/depository:/output/depository:ro
            - /home1/data/STARK/services/rnaseq/fusions:/services/rnaseq/fusions:rw
            - /home1/data/STARK/config/rnaseq/fusions:/config/rnaseq/fusions:ro
            - /home1/data/STARK/config/rnaseq/fusions/listener/launcher.py:/app/bin/config/launcher.py:ro
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - stark_stark
        depends_on:
            stark-module-rnaseq-submodule-fusions-service-cli:
                condition: service_healthy

networks:
    stark_stark:
        external: true